#set -g @catppuccin_flavor 'latte'
#run '~/.config/tmux/plugins/tmux/catppuccin.tmux'
# Themes setting

# unbind default prefix and set it to ctrl-a
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# make delay shorter
set -sg escape-time 0



#### key bindings ####

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux.conf reloaded!"

# quickly open a new window
bind N new-window

# synchronize all panes in a window
bind y setw synchronize-panes



# pane movement shortcuts (same as vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# enable mouse support for switching panes/windows
set -g mouse on


#### copy mode : vim ####

# set vi mode for copy mode
setw -g mode-keys vi

# copy mode using 'Esc'
unbind [
bind Escape copy-mode


# paste using 'p'
unbind p
bind p paste-buffer

#

bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

#setw -g  terminal-features clipboard

set-option -g focus-events on
set -g default-terminal "$TERM"
set -as terminal-features ",alacritty*:RGB"
set -ag terminal-overrides ",$TERM:Tc"


## plugins 
#set -g @plugin tmux-plugins/tmux-sidebar \
#set -g @plugin wfxr/tmux-power \
#set -g @plugin dracula/tmux \
#set -g @plugin egel/tmux-gruvbox \
#set -g @tpm-plugins  '                #\
set -g @plugin     tmux-plugins/tpm                  #\
set -g @plugin     tmux-plugins/tmux-copycat         #\
set -g @plugin     tmux-plugins/tmux-open            #\
set -g @plugin     tmux-plugins/tmux-sensible        #\
set -g @plugin     tmux-plugins/tmux-yank            #\
set -g @plugin     tmux-plugins/tmux-fpp             #\
set -g @plugin     olimorris/tmux-pomodoro-plus      #\
set -g @plugin     alexwforsythe/tmux-which-key      #\
set -g @plugin     rickstaa/tmux-notify              #\
set -g @plugin     omerxx/tmux-floax                 #\
set -g @plugin     lloydbond/tmux-floating-terminal  #\
set -g @plugin     tmux-plugins/tmux-resurrect       #\
set -g @plugin     MunifTanjim/tmux-mode-indicator   #\
set -g @plugin     yellowtaoworkshop/nord-tmux       #\
#'

## Plugins Options
set -g @floax-bind "F"
set -g @floax-bind-menu "M"
set -g @floax-text-color "white"


# Pane styling options
set-option -g pane-border-format " #T "
set-option -g pane-border-lines single
set-option -g pane-border-indicators off
set-option -g pane-border-status top

#set -g status-position top
set -g status-right-length 100
set -g status-left-length 100

run '~/.config/tmux/plugins/tpm/tpm'
# TODO have no idea
run '~/.config/tmux/plugins/tmux-pomodoro-plus/pomodoro.tmux'

